environment: qa

apphost: openshift4

label:
  name: marcaspnet3core

container:
  name: marcaspnet3
  pullPolicy: Always
  image: quay.io/marcf5/dotnetcore
  tag: latest
  port: 8080

replicas: 3

service:
  port: 8080
  type: ClusterIP
