apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "9"
    creationTimestamp: "2020-03-25T07:59:20Z"
    generation: 9
    labels:
      app: aspnet3core
    name: aspnet3release-deployment
    namespace: dotnetcore2
    resourceVersion: "416229"
    selfLink: /apis/apps/v1/namespaces/dotnetcore2/deployments/aspnet3release-deployment
    uid: 604d4248-8026-44e6-aa6d-4d56bb1a36ac
  spec:
    progressDeadlineSeconds: 600
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: aspnet3core
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: aspnet3core
          environment: development
      spec:
        containers:
        - env:
          - name: apphost
            value: k8s
          - name: appenvironment
            value: development
          image: quay.io/marcf5/dotnetcore
          imagePullPolicy: Always
          name: aspnet3
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: marcinternalregistrysecret
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2020-03-25T07:59:20Z"
      lastUpdateTime: "2020-03-25T07:59:20Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - lastTransitionTime: "2020-03-25T17:56:27Z"
      lastUpdateTime: "2020-03-25T17:56:31Z"
      message: ReplicaSet "aspnet3release-deployment-6ff5896d54" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 9
    replicas: 4
    unavailableReplicas: 4
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
